### ISSUE TITLE
Create Page Routes

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#11]
Welcome to Hack Tanya! This will be your first ticket on GreenZone!!

**Task:** Create `monitoring-platform.tsx` , `landing.tsx` , `about.tsx`, `methodology.tsx`, `contact.tsx`, `login.tsx`, `summary-stats.tsx` and create a `NavBar.tsx` to link all of these pages together. NavBar should be persistent on every page.

**Context:** For the `NavBar.tsx` we are going to incorporate some atomic design into this ticket to make it easier to build up our components and make it more adaptable to a small screen. So for example the `NavBar` will be implemented as a "molecule" made up of multiple "atoms". One atom might be a `TextBox` or a `Button`. Take a look at the `lagos-volunteers` repo under  `frontend/src/components/molecules/AppBar` to get an idea of how to implement this.

- [x] Create Monitoring Platform page and other pages mentioned above under `frontend/src/components/pages` directory. These pages don't require content as yet. I just need you to create the files. 
- [x]  Create the NavBar that will be fixed at the top of the webpage. You will should use the `Button` and `Textbox` atoms in `frontend/src/components/atoms` to build up this `NavBar`. In this `NavBar` you should have a button for each of the pages mentioned above. 
- [x] Link the pages: Now you will have to go into the `NavBar` to add some code to link the pages such that if you click on the `Monitoring-Platform` button on the `NavBar` it will take you to that page.
- [x] Create a DropDown: This will come into action when the page size is small, and will convert all the `NavBar` buttons into drop downs to adjust to the size of the screen. The links from above should still work.

**Working Directory:** 
- `frontend/src/components/atoms`
- `frontend/src/components/molecules`
- `frontend/src/pages`

**Tutorials:**

- [Fundamentals of Next.js pages](https://nextjs.org/docs/pages)
- [Routing](https://nextjs.org/docs/app/building-your-application/routing)
- [Video Tutorial on Page Routing](https://www.youtube.com/watch?v=vwg4Wrk-kWE&ab_channel=NetNinja)
