### ISSUE TITLE
Develop Main Map Page (part 2)

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#14]
**Task** : Add Initial layers to main map to display the different Provinces and Counties using a SHP/GeoJSON file.

**Features:** 
- [ ] Add button to toggle on and off the display of different Provinces in Mongolia (Add name to the Provinces) - need to provide files
- [ ] Add button to toggle on and off the display of different Counties in Mongolia
- [ ] Should be able to click on and drag the map around
- [ ]  Add OnClick functionality to each Province. When a Province is clicked, it will highlight that region and then zoom in on the region. Maybe also provide functionality to exit view and return to original map view.

Example Image Showing Provinces Toggled On: 
![Image](https://github.com/user-attachments/assets/6fd7f7dd-cc6f-4df3-9a40-1bc23b3c1d92)
Example Image Showing Counties and Provinces Toggled On: 
![Image](https://github.com/user-attachments/assets/68b2210e-aec7-4f2a-9f9c-4a65800107eb)

**Working Directory**:
- `frontend/src/app/components/Map.tsx`

**Required Technology**
- Leaflet.js
- Will need a SHP/GeoJSON file providing data for each province and county. Ask TL for this file.
