### ISSUE TITLE
Implement Dual Language Support Part 1

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#34]
**Task:** Research methods to implement dual language technique on the website. 

Tutorials:
[I18](https://locize.com/blog/react-i18next/)

**Comment by LiuBrianna** [comment]
**Goal:** Create a way so that users are able to switch between two languages (possibly more) that updates the pages live.

**Prerequites:** 
Node.js 
Npm
React >= 18.0.0

**Dependencies** 
[I18next](https://www.i18next.com/)
Core translation library
[React-i18next](https://react.i18next.com/) 
React i18n framework
[I18next-browser-languagedetector](https://github.com/i18next/i18next-browser-languageDetector) 
Detects the user's browser language (useful for defaulting to English or Mongolian)
Note: This could enhance the user experience by auto-detecting the preferred language.
[I18next-http-backend](https://www.npmjs.com/package/i18next-http-backend/v/1.0.10)
Fetches translations from the backend 

**Current possible paths explored:**

- https://locize.com/blog/react-i18next/#why-i18next 

This resource gives a broad overview of what i18next can handle translation. 
Problem: However, we want all our translations in the backend and we then pull to the frontend. 
https://dev.to/franklin030601/building-a-multi-language-app-with-react-js-2och#5 

- This resource is more aligned with what we want to have. The translation is separate. 

Problem: Translations are stored on the frontend. Additionally, the guide uses Vite, requiring significant project restructuring if we choose to follow this path.
We might bypass Vite and adapt the process to our existing setup.
Demo code: https://multi-lang-app-react.netlify.app/ 

- https://www.youtube.com/watch?v=IophVqi_SEc 

Source code: https://github.com/monsterlessonsacademy/monsterlessonsacademy/tree/420-react-multi-language-website 
This resource uses i18next and has an express backend (using an API to pull from the backend). However, the issue is that this codebase is in JavaScript so it will take a bit of time to convert the code to typescript

Current Timeline:

- [ ] Research 3+ possible ways to implement a multi-langauge application
- [ ] Explore each pros and cons of the possibiblites 
- [ ] Proof of reproducatibility on a small scale ← current on this step
- [ ] Sandbox on current GreenZon repo
- [ ] Fully integrate it with other part of greenzone
