### ISSUE TITLE
Populate the Map with Circles instead of Hexagons

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#73]
**Task:** Populate map with circular cells instead of hexagonal cells. 

**Features:** 

- [x] Before our cells were hexagonal. but our partners want to use circular cells. We don't have to change the name of every hexagon in the code to circular, but just keep in mind that we're using circles now and not hexagons. I already updated the backend to have the circles instead of the hexagons so this task is more of a check to make sure you can see the circles when you loaded.

- [x] When the user clicks on the "Carrying Capacity" button in the SidePanel, all the circles should show up. So it's like that "Toggle hexagon" button from last time, but this time you'll remove that "Toggle Hexagon" and use this "Carrying Capacity" button in the SidePanel. Once all the circles are loaded in another ticket you will filter these circles based on 'Below, At or Above' Capacity toggles. 

- [x] Colour the circles based on their "bm_pred" value. Open Up PostMan and call `/GET` hexagons endpoint to see what the attributes of a hexagon are. (If you get an overflow or too much data error tell me, I'll reduce the amount of info). Notice the varying values of the "bm_pred" field. Colour according to this scale:
  - Below: <=0.4 --> Green
  - At: 0.4 > and <0.6 --> Yellow
  - Above: >= 0.6 --> Red 

**Examples:**
### Image when the Carrying Capacity toggle is on
![Image](https://github.com/user-attachments/assets/7f26619b-b00e-48d6-91cd-28e06a525637)

### Image of Circles Loaded Without Colour
![Image](https://github.com/user-attachments/assets/ce89c966-e0c0-4461-8187-3f0b603c6a0a)

**Estimated Time**: 4 hrs

**Working Directory:**
