### ISSUE TITLE
Bug Fixes for Monitoring Platform and SidePanel Integration

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#74]
**Task:** Zoom in on a Province when it is searched in the SearchBar

**Features:**

- [x]  Remove the county borders for now. The borders don't seem to align with the Province Borders and it's making the map look confusing. So for now remove the county borders and the toggle for it.
- [x] When a Province is Zoomed In on, the map seems to be darkened. We want the map to remain the same opacity, don't darken it.
- [ ]  Right now the province zooms when it's clicked and it's information shows up in the SidePanel. You should also do the same when the Province is searched and also display it's information in the SidePanel (this part I think is already done).
- [x] When a province is clicked the first time, the map zooms in and the sidepanel is shown, but once we exit out of the sidepanel, return to the map and try clicking again, it zooms in but the sidepanel doesn't show anymore. Ideally the sidepanel should still show when exit and click on a province again. I think this might be a state management issue with the way the sidepanel component is loaded.
- [ ] When the map is loaded initially, it should already show the Province borders. Im not sure if it's a problem on my end but when I load the map, I have to first click either the "Toggle Hex/Counties" button for the Province border to show and persist. I think there might be a bug in the way the Provinces are loaded when the map is loaded. 
- [x] I think the zoom in on a Province is fixed, is it possible to set the zoom in based on the size of a Province? I know that I will need to change the "land_area" field in the backend (because it's dummy data and they all have the same land_area), but you can try changing them (just one not all of them) manually in the frontend and then checking if you can zoom based on the size of a Province. This is because with the current zoom parts of some Provinces are cut because they're too big.

Figma Designs:
