### ISSUE TITLE
Adjust the Livestock Graphs and Implement the Context Manager

### ISSUE THREAD

**Issue by DannyThorne01** [cornellh4i/greenzone#81]
**Task:** With the new Supabase PostgreSQL database, connect the Livestock Graphs for Provinces and Counties to the new database. This is a Fullstack ticket.

**Features:** Before these graphs were connected to the MongoDB, where it queried information for a specific province/county for a specific year. Now we want you to: 
  - [x] Create two SQL functions in `backend/src/controllers` using Supabase logic to query the livestock data in the province_livestock and county_livestock database. The function should take two parameters, the province/county name and the year of interest.
  - [x] Create two routes in `backend/src/routes.ts` where you will execute the above functions when a specific API endpoint is called. You get liberty to name the endpoint, just give it a proper name and document the endpoint name in the Notion with it's role (GET, POST, or UPDATE) and a description of what it does.
  - [x] In the frontend, in the `SidePanel.tsx` fetch the data associated with a specific province/county and a specific year. The province/county and year should specific in the `provinceName` and `selectedYear` state variables. Feed this data to the `barchart` component. Since the data is coming in a different format you'll have to manipulate it so that it's compatible with the graphs. 
  - [x] Now when a province/county (for now I think only the province works) is clicked a SidePanel should pop up showing the livestock statistics for that province/county.

**Estimated Time:**  
  - 2 hours to create the SQL functions
  - 1 hour to create the routes
  - 3-4 hours to adjust the frontend (because you'll also have to adjust the way information is being fed to `graphs` components)
